twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        app_webpack_folder: '%env(APP_WEBPACK_FOLDER)%'

when@test:
    twig:
        strict_variables: true
