version: '3.5'

services:
    php:
        working_dir: /var/www/dev-php
        image: scalecommerce/dev-php:7.3.8-v2
        volumes:
            - .:/var/www/dev-php:cached
        environment:
            APP_DEBUG: "true"
        ports:
            - 127.0.0.1:80:80
        links:
            - db
            - mysql
            - mailhog
    db:
        image: yandex/clickhouse-server:21.2.7
        ports:
            - 127.0.0.1:9000:9000
            - 127.0.0.1:8123:8123
            - 127.0.0.1:9009:9009
            - 127.0.0.1:9004:9004
        environment:
            CLICKHOUSE_DB: "logs"
    mysql:
        image: percona:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - 3306:3306
    mailhog:
        image: mailhog/mailhog
        ports:
            - 127.0.0.1:8025:8025
